### ISSUE TITLE
Check multi monitor maximizing on linux

### ISSUE THREAD

**Issue by bendikMichal** [bendikMichal/pyretro-gui#3]
....

**Comment by bendikMichal** [comment]
Could prove useful
https://stackoverflow.com/questions/26524133/xlib-get-desktop-work-area

**Comment by Clutchnp** [comment]
I just noticed this issue, while I dont have multiple monitor setup to test this , this should be fixed by #6. Can you check?

**Comment by bendikMichal** [comment]
Can't really check right now either as I do not have access to the 2nd monitor rn.

**Comment by bendikMichal** [comment]
Will keep in mind

**Comment by Clutchnp** [comment]
Checked,[this works without issue](https://vlix.io/video/69e8401880e3c1836fbe/).

**Comment by bendikMichal** [comment]
Great, thanks 👍.
