### ISSUE TITLE
Getting around missing _NET_WORKAREA in some linux de's

### ISSUE THREAD

**Issue by bendikMichal** [bendikMichal/pyretro-gui#4]
KDE plasma has _NET_WORKAREA, but i3 does not...

**Comment by Clutchnp** [comment]
I dont think we need a maximize button in tiling wms, as users can just change the window from tiling to floating and vice-versa as they please, we should remove the window maximize option all together if minimize is not supported , as if minimize is not supported the window manager probably is tiling wm in which case maximize button wont do any good

**Comment by bendikMichal** [comment]
We can remove maximize option in tilig wm's theoretically, need to also check how resizing would behave. Is it only missing in tiling window mangaers or are there other NON tiling desktops that do not have it?

**Comment by Clutchnp** [comment]
we should only support window managers complying to [ewmh](https://specifications.freedesktop.org/wm-spec/latest/)  which  all known window-managers/desktop environment follow,we don't need to support otherwise, (even i3 complies with it,just not fully)

**Comment by bendikMichal** [comment]
A cool read actually. Seems reasonable, let's go with removing the maximize button when minimize is not supported as you mentioned previously.

**Comment by bendikMichal** [comment]
Fixed by @Clutchnp in [this](https://github.com/bendikMichal/pyretro-gui/pull/8) pr.
